<?php

namespace App\Http\Requests;

use App\Models\InvitationLink;
use Illuminate\Foundation\Http\FormRequest;

/**
 * validates generation of an `InvitationLink` for a Course.
 * `course_id`/`org_id`/`token`/`created_by` are intentionally absent from
 * these rules: `course_id` is resolved from the route-bound `{course}`
 * segment, `org_id` from `OrgScope::booted()`'s `creating` hook, and
 * `token`/`created_by` are generated by `InvitationLinkController::store()`.
 */
class StoreInvitationLinkRequest extends FormRequest
{
    public function authorize(): bool
    {
        return (bool) $this->user()?->can('create', [InvitationLink::class, $this->route('course')]);
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'max_uses' => ['nullable', 'integer', 'min:1'],
            'expires_at' => ['nullable', 'date', 'after:now'],
        ];
    }
}
